spring.application.name=hobby

# H2 데이터베이스 활성화
spring.h2.console.enabled=true

# JPA가 테이블 모두 생성 후에, data.sql 실행 되도록 순서 보장
spring.jpa.defer-datasource-initialization=true

# 특정 패키지의 로그 레벨을 DEBUG로 설정
logging.level.com.project.hobby=DEBUG